## No Method, for the VOC test performance results with RAW model
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method NoMethod --cluster_method one --which_internal_activations logits --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_NoMethod.log 2>&1 &

## RQ1
# Vanilla runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method L1_cl_stride --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_L1_one.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method L1_cl_stride --cluster_method KMeans --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_L1_KMeans.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method L1_cl_stride --cluster_method KMeans_10 --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_L1_KMeans_10.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method L1_cl_stride --cluster_method HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_L1_HDBSCAN.log 2>&1 &

nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method L2_cl_stride --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_L2_one.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method L2_cl_stride --cluster_method KMeans --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_L2_KMeans.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method L2_cl_stride --cluster_method KMeans_10 --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_L2_KMeans_10.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method L2_cl_stride --cluster_method HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_L2_HDBSCAN.log 2>&1 &

nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method Cosine_cl_stride --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_Cosine_one.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method Cosine_cl_stride --cluster_method KMeans --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_Cosine_KMeans.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method Cosine_cl_stride --cluster_method KMeans_10 --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_Cosine_KMeans_10.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method Cosine_cl_stride --cluster_method HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_Cosine_HDBSCAN.log 2>&1 &

# SDR
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method L1Ivis --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_L1Ivis_One.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method L1Ivis --cluster_method KMeans --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_L1Ivis_KMeans.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method L1Ivis --cluster_method KMeans_10 --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_L1Ivis_KMeans_10.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method L1Ivis --cluster_method HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_L1Ivis_HDBSCAN.log 2>&1 &

nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method L2Ivis --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_L2Ivis_One.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method L2Ivis --cluster_method KMeans --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_L2Ivis_KMeans.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method L2Ivis --cluster_method KMeans_10 --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_L2Ivis_KMeans_10.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method L2Ivis --cluster_method HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_L2Ivis_HDBSCAN.log 2>&1 &

nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method CosineIvis --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_CosineIvis_One.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method CosineIvis --cluster_method KMeans --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_CosineIvis_KMeans.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method CosineIvis --cluster_method KMeans_10 --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_CosineIvis_KMeans_10.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method CosineIvis --cluster_method HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_CosineIvis_HDBSCAN.log 2>&1 &

# EUL
nohup python ood_evaluation.py --enhanced_unk_localization --benchmark conf_thr_test --ood_method L1_cl_stride --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_EUL_L1_one.log 2>&1 &
nohup python ood_evaluation.py --enhanced_unk_localization --benchmark conf_thr_test --ood_method L1_cl_stride --cluster_method KMeans --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_EUL_L1_KMeans.log 2>&1 &
nohup python ood_evaluation.py --enhanced_unk_localization --benchmark conf_thr_test --ood_method L1_cl_stride --cluster_method KMeans_10 --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_EUL_L1_KMeans_10.log 2>&1 &
nohup python ood_evaluation.py --enhanced_unk_localization --benchmark conf_thr_test --ood_method L1_cl_stride --cluster_method HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_EUL_L1_HDBSCAN.log 2>&1 &

nohup python ood_evaluation.py --enhanced_unk_localization --benchmark conf_thr_test --ood_method L2_cl_stride --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_EUL_L2_one.log 2>&1 &
nohup python ood_evaluation.py --enhanced_unk_localization --benchmark conf_thr_test --ood_method L2_cl_stride --cluster_method KMeans --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_EUL_L2_KMeans.log 2>&1 &
nohup python ood_evaluation.py --enhanced_unk_localization --benchmark conf_thr_test --ood_method L2_cl_stride --cluster_method KMeans_10 --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_EUL_L2_KMeans_10.log 2>&1 &
nohup python ood_evaluation.py --enhanced_unk_localization --benchmark conf_thr_test --ood_method L2_cl_stride --cluster_method HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_EUL_L2_HDBSCAN.log 2>&1 &

nohup python ood_evaluation.py --enhanced_unk_localization --benchmark conf_thr_test --ood_method Cosine_cl_stride --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_EUL_Cosine_one.log 2>&1 &
nohup python ood_evaluation.py --enhanced_unk_localization --benchmark conf_thr_test --ood_method Cosine_cl_stride --cluster_method KMeans --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_EUL_Cosine_KMeans.log 2>&1 &
nohup python ood_evaluation.py --enhanced_unk_localization --benchmark conf_thr_test --ood_method Cosine_cl_stride --cluster_method KMeans_10 --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_EUL_Cosine_KMeans_10.log 2>&1 &
nohup python ood_evaluation.py --enhanced_unk_localization --benchmark conf_thr_test --ood_method Cosine_cl_stride --cluster_method HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_EUL_Cosine_HDBSCAN.log 2>&1 &

## RQ2
# Logits
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method MSP --cluster_method one --which_internal_activations logits --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_MSP.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method Energy --cluster_method one --which_internal_activations logits --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_Energy.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --ood_method ODIN --cluster_method one --which_internal_activations logits --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_ODIN.log 2>&1 &


## Fusion
# or
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy or --ood_method fusion-MSP-Energy --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_or_MSP-Energy.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy or --ood_method fusion-MSP-ODIN --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_or_MSP-ODIN.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy or --ood_method fusion-MSP-Cosine_cl_stride --cluster_method HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_or_MSP-CosineHDBSCAN.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy or --ood_method fusion-MSP-CosineIvis --cluster_method HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_or_MSP-CosineIvisHDBSCAN.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy or --ood_method fusion-Cosine_cl_stride-CosineIvis --cluster_method KMeans_10-HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_or_CosineKMeans10-CosineIvisHDBSCAN.log 2>&1 &
#
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy or --ood_method fusion-MSP-L1_cl_stride --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_or_MSP-L1one.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy or --ood_method fusion-MSP-L1Ivis --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_or_MSP-L1Ivisone.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy or --ood_method fusion-L1_cl_stride-CosineIvis --cluster_method one-HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_or_L1one-CosineIvisHDBSCAN.log 2>&1 &

# and
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy and --ood_method fusion-MSP-Energy --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_and_MSP-Energy.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy and --ood_method fusion-MSP-ODIN --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_and_MSP-ODIN.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy and --ood_method fusion-MSP-Cosine_cl_stride --cluster_method HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_and_MSP-CosineHDBSCAN.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy and --ood_method fusion-MSP-CosineIvis --cluster_method HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_and_MSP-CosineIvisHDBSCAN.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy and --ood_method fusion-Cosine_cl_stride-CosineIvis --cluster_method KMeans_10-HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_and_CosineKMeans10-CosineIvisHDBSCAN.log 2>&1 &
#
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy and --ood_method fusion-MSP-L1_cl_stride --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_and_MSP-L1one.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy and --ood_method fusion-MSP-L1Ivis --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_and_MSP-L1Ivisone.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy and --ood_method fusion-L1_cl_stride-CosineIvis --cluster_method one-HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_and_L1one-CosineIvisHDBSCAN.log 2>&1 &

# score
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy score --ood_method fusion-MSP-Energy --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_score_MSP-Energy.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy score --ood_method fusion-MSP-ODIN --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_score_MSP-ODIN.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy score --ood_method fusion-MSP-Cosine_cl_stride --cluster_method HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_score_MSP-CosineHDBSCAN.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy score --ood_method fusion-MSP-CosineIvis --cluster_method HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_score_MSP-CosineIvisHDBSCAN.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy score --ood_method fusion-Cosine_cl_stride-CosineIvis --cluster_method KMeans_10-HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_score_CosineKMeans10-CosineIvisHDBSCAN.log 2>&1 &
#
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy score --ood_method fusion-MSP-L1_cl_stride --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_score_MSP-L1one.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy score --ood_method fusion-MSP-L1Ivis --cluster_method one --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_score_MSP-L1Ivisone.log 2>&1 &
nohup python ood_evaluation.py --benchmark conf_thr_test --fusion_strategy score --ood_method fusion-L1_cl_stride-CosineIvis --cluster_method one-HDBSCAN --which_internal_activations ftmaps_and_strides --which_split train_val  --load_ind_activations --ood_datasets owod coco_ood coco_mixed --device 0 --ind_info_creation_option valid_preds_one_stride  --conf_thr_train 0.15 --conf_thr_test 0.15 --tpr_thr 0.95 --model_path runs_OWOD/20250517_1728_owod_t1_yolo11l_from_scratch/weights/best.pt --ind_dataset owod --ind_split train --owod_task_ind t1 --ood_split val --owod_task_ood t1 > logs/benchmark_V11_conf_trest_score_L1one-CosineIvisHDBSCAN.log 2>&1 &
